name: Build and Deploy to ECR Public

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      ECR_IMAGE: public.ecr.aws/b9b6c8v5/blogapi:latest  # Correct public ECR image reference
      AWS_DEFAULT_REGION: us-west-1

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up QEMU for amd64
        if: runner.os == 'Linux'
        run: |
          docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
        shell: bash

      - name: Set up Docker for amd64
        uses: docker/setup-qemu-action@v2
        with:
          platforms: linux/amd64

      - name: Set up Docker
        uses: docker/setup-buildx-action@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_DEFAULT_REGION }}

      - name: Login to Amazon ECR Public
        run: |
          echo "Logging in to Amazon ECR Public..."
          aws ecr-public get-login-password --region us-east-1 | docker login --username AWS --password-stdin public.ecr.aws
      - name: Build and push Docker image
        run: |
          echo "Creating buildx builder..."
          docker buildx create --use
          docker buildx inspect --bootstrap
          echo "Building and pushing Docker image..."
          docker buildx build --platform linux/amd64 -t ${{ env.ECR_IMAGE }} --push .